
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>
#include <gmodule.h>

G_BEGIN_DECLS

/* enumerations from "amtk-factory.h" */

G_MODULE_EXPORT
GType amtk_factory_flags_get_type (void);
#define AMTK_TYPE_FACTORY_FLAGS (amtk_factory_flags_get_type())

G_END_DECLS

/* Generated data ends here */

