
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>
#include <gmodule.h>

G_BEGIN_DECLS

/* enumerations from "tepl-buffer.h" */

G_MODULE_EXPORT
GType tepl_selection_type_get_type (void);
#define TEPL_TYPE_SELECTION_TYPE (tepl_selection_type_get_type())

/* enumerations from "tepl-file-saver.h" */

G_MODULE_EXPORT
GType tepl_file_saver_flags_get_type (void);
#define TEPL_TYPE_FILE_SAVER_FLAGS (tepl_file_saver_flags_get_type())

/* enumerations from "tepl-file.h" */

G_MODULE_EXPORT
GType tepl_newline_type_get_type (void);
#define TEPL_TYPE_NEWLINE_TYPE (tepl_newline_type_get_type())

/* enumerations from "tepl-gutter-renderer-folds.h" */

G_MODULE_EXPORT
GType tepl_gutter_renderer_folds_state_get_type (void);
#define TEPL_TYPE_GUTTER_RENDERER_FOLDS_STATE (tepl_gutter_renderer_folds_state_get_type())

/* enumerations from "tepl-info-bar.h" */

G_MODULE_EXPORT
GType tepl_info_bar_location_get_type (void);
#define TEPL_TYPE_INFO_BAR_LOCATION (tepl_info_bar_location_get_type())

/* enumerations from "tepl-settings.h" */

G_MODULE_EXPORT
GType tepl_settings_theme_variant_get_type (void);
#define TEPL_TYPE_SETTINGS_THEME_VARIANT (tepl_settings_theme_variant_get_type())

G_END_DECLS

/* Generated data ends here */

